# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kofiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(verbose_name='date_uploaded')),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kofiapp.CoffeePic')),
            ],
        ),
    ]
