# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kofiapp', '0002_coffeepic_coffeetag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeepic',
            name='file_name',
        ),
        migrations.AddField(
            model_name='coffeepic',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
