# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kofiapp', '0003_auto_20170723_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeepic',
            name='processed_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
