# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kofiapp', '0007_auto_20170724_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeetag',
            name='tag',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
