# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kofiapp', '0008_auto_20170724_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(db_index=True, max_length=255)),
                ('premium_member', models.BooleanField(db_index=True, default=False)),
                ('birthdate', models.DateField()),
                ('birthsign', models.CharField(blank=True, max_length=50, null=True)),
                ('marital', models.CharField(choices=[('U', 'Unknown'), ('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('E', 'Engaged'), ('P', 'Platonic')], db_index=True, default='UNK', max_length=1)),
                ('graduation', models.CharField(choices=[('UNK', 'Unknown'), ('PRI', 'Primary'), ('MID', 'Middle'), ('HIG', 'High'), ('UNI', 'Univercity'), ('POS', 'Post Grad'), ('DOR', 'Doctorate'), ('PHD', 'Phd'), ('LEF', 'Left')], db_index=True, default='UNK', max_length=3)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
