# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kofiapp', '0009_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fortune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submit', models.DateTimeField(auto_now_add=True, verbose_name='date_submitted')),
                ('date_processed', models.DateTimeField(null=True, verbose_name='date_processed')),
                ('processed', models.BooleanField(default=False)),
                ('fortune_predicted', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kofiapp.Customer')),
                ('pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kofiapp.CoffeePic')),
            ],
        ),
    ]
