# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kofiapp', '0010_fortune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fortune',
            name='processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
