# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kofiapp', '0011_auto_20170725_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=10),
        ),
    ]
